FROM	alpine:3.12.3

#Update and install utils
RUN apk update
RUN apk add grafana --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache
RUN apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache
RUN mkdir /etc/telegraf 
ADD ./srcs/telegraf.conf /etc/telegraf/

#Conf
ADD ./srcs/datasource.yaml /usr/share/grafana/conf/provisioning/datasources/
ADD ./srcs/dashboard.yaml /usr/share/grafana/conf/provisioning/dashboards/
ADD ./dashboards/*.json /usr/share/grafana/conf/provisioning/dashboards/

#Run
ADD	./srcs/setup.sh .
RUN	chmod 777 setup.sh

EXPOSE 3000

CMD		[ "/bin/ash", "/setup.sh" ]
